export const DONATION_DESTINATION_WALLET = '44LfWhS3PSYf7GxUE2evtTXvT5nYRe6jEMvTZd3YJ9E2';
export const DONATION_AMOUNT_SOL_OPTIONS = [1, 5, 10];
export const DEFAULT_DONATION_AMOUNT_SOL = 1;
export const MEMO_DESTINATION_WALLET = '44LfWhS3PSYf7GxUE2evtTXvT5nYRe6jEMvTZd3YJ9E2';
export const DEFAULT_DESTINATION_WALLET = '44LfWhS3PSYf7GxUE2evtTXvT5nYRe6jEMvTZd3YJ9E2';
